### ISSUE TITLE
大佬，如果想获取心跳返回的人气数据该怎么写呢~

### ISSUE THREAD

**Issue by why0209** [FrothierNine346/BilibiliLiveMSGHandler#1]
如题，感谢大佬！

**Comment by FrothierNine346** [comment]
更新至项目最新版本，MessageHandler的MessageCmd设置为_HEARTBEAT即可。具体格式请看[MessageManager.cs](https://github.com/FrothierNine346/BilibiliLiveMSGHandler/blob/main/BilibiliLiveMSGHandler/MessageManager/MessageManager.cs#L136)
